apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-service
  labels:
    service: backend
spec:
  containers:
    - name: spring-boot-service
      image: ankitkr09/boot
      ports:
        - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: service-node-port
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31515
  selector:
    service: backend